# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlateRecognition_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1114, 792)
        MainWindow.setMinimumSize(QtCore.QSize(1114, 792))
        MainWindow.setMaximumSize(QtCore.QSize(1114, 792))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images_test/result.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("#MainWindow{border-image: url(:/newPrefix/images_test/back.png);}\n"
"\n"
"#QInputDialog{border-image: url(:/newPrefix/images_test/light.png);}\n"
"\n"
"QLabel{border:5px;}\n"
"QLabel::hover {\n"
"border:0px;}\n"
"\n"
"QMenuBar{border-color:transparent;}\n"
"QToolButton[objectName=pushButton_doIt]{\n"
"border:5px;}\n"
"\n"
"QToolButton[objectName=pushButton_doIt]:hover {\n"
"image:url(:/newPrefix/images_test/run_hover.png);}\n"
"\n"
"QToolButton[objectName=pushButton_doIt]:pressed {\n"
"image:url(:/newPrefix/images_test/run_pressed.png);}\n"
"\n"
"QScrollBar:vertical{\n"
"background:transparent;\n"
"padding:2px;\n"
"border-radius:8px;\n"
"max-width:8px;}\n"
"\n"
"QScrollBar::handle:vertical{\n"
"background:#9acd32;\n"
"min-height:8px;\n"
"border-radius:8px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover{\n"
"background:#9eb764;}\n"
"\n"
"QScrollBar::handle:vertical:pressed{\n"
"background:#9eb764;\n"
"}\n"
"QScrollBar::add-page:vertical{\n"
"background:none;\n"
"}\n"
"                               \n"
"QScrollBar::sub-page:vertical{\n"
"background:none;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"background:none;}\n"
"                                 \n"
"QScrollBar::sub-line:vertical{\n"
"background:none;\n"
"}\n"
"QScrollArea{\n"
"border:0px;\n"
"}\n"
"\n"
"QScrollBar:horizontal{\n"
"background:transparent;\n"
"padding:0px;\n"
"border-radius:6px;\n"
"max-height:6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal{\n"
"background:#9acd32;\n"
"min-width:8px;\n"
"border-radius:6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{\n"
"background:#9eb764;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:pressed{\n"
"background:#9eb764;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal{\n"
"background:none;\n"
"}\n"
"\n"
"QScrollBar::sub-page:horizontal{\n"
"background:none;\n"
"}\n"
"QScrollBar::add-line:horizontal{\n"
"background:none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal{\n"
"background:none;\n"
"}\n"
"QToolButton::hover{\n"
"border:0px;\n"
"} ")
        MainWindow.setIconSize(QtCore.QSize(25, 25))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(356, 608, 755, 180))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(569, 150))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 180))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setWordWrap(False)
        self.tableWidget.setRowCount(6)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 2, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.label_display = QtWidgets.QLabel(self.centralwidget)
        self.label_display.setGeometry(QtCore.QRect(356, 120, 753, 483))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_display.sizePolicy().hasHeightForWidth())
        self.label_display.setSizePolicy(sizePolicy)
        self.label_display.setMinimumSize(QtCore.QSize(753, 483))
        self.label_display.setMaximumSize(QtCore.QSize(753, 483))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.label_display.setFont(font)
        self.label_display.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_display.setStyleSheet("border-image: url(:/newPrefix/images_test/ini-image.png);")
        self.label_display.setAlignment(QtCore.Qt.AlignCenter)
        self.label_display.setObjectName("label_display")
        self.label_picLocation = QtWidgets.QLabel(self.centralwidget)
        self.label_picLocation.setGeometry(QtCore.QRect(360, 73, 37, 40))
        self.label_picLocation.setMinimumSize(QtCore.QSize(30, 30))
        self.label_picLocation.setMaximumSize(QtCore.QSize(50, 40))
        self.label_picLocation.setStyleSheet("border-image: url(:/newPrefix/images_test/Ordinateur.png);")
        self.label_picLocation.setText("")
        self.label_picLocation.setObjectName("label_picLocation")
        self.label_location = QtWidgets.QLabel(self.centralwidget)
        self.label_location.setGeometry(QtCore.QRect(416, 76, 185, 35))
        self.label_location.setMinimumSize(QtCore.QSize(0, 30))
        self.label_location.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(18)
        self.label_location.setFont(font)
        self.label_location.setObjectName("label_location")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(378, 8, 614, 35))
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: italic 20pt \"隶书\";")
        self.label_title.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_title.setObjectName("label_title")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 350, 793))
        self.scrollArea.setMinimumSize(QtCore.QSize(250, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(350, 16777215))
        self.scrollArea.setStyleSheet("background-color: rgb(233, 239, 251);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 350, 793))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.label_class_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_class_3.setGeometry(QtCore.QRect(4, 4, 347, 70))
        self.label_class_3.setMinimumSize(QtCore.QSize(100, 70))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_class_3.setFont(font)
        self.label_class_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_class_3.setObjectName("label_class_3")
        self.label_pic = QtWidgets.QLabel(self.centralwidget)
        self.label_pic.setGeometry(QtCore.QRect(4, 82, 322, 121))
        self.label_pic.setMinimumSize(QtCore.QSize(251, 121))
        self.label_pic.setStyleSheet("border-image: url(:/newPrefix/images_test/person.png);")
        self.label_pic.setText("")
        self.label_pic.setObjectName("label_pic")
        self.textEdit_model = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_model.setGeometry(QtCore.QRect(52, 238, 283, 30))
        self.textEdit_model.setMinimumSize(QtCore.QSize(0, 30))
        self.textEdit_model.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(12)
        self.textEdit_model.setFont(font)
        self.textEdit_model.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.textEdit_model.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(0, 170, 255);\n"
"color: rgb(0, 170, 255);")
        self.textEdit_model.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_model.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_model.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textEdit_model.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_model.setReadOnly(True)
        self.textEdit_model.setObjectName("textEdit_model")
        self.toolButton_model = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_model.setGeometry(QtCore.QRect(16, 236, 30, 30))
        self.toolButton_model.setMinimumSize(QtCore.QSize(28, 30))
        self.toolButton_model.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton_model.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_model.setAutoFillBackground(False)
        self.toolButton_model.setStyleSheet("background-color: transparent;")
        self.toolButton_model.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/images_test/folder_web.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_model.setIcon(icon1)
        self.toolButton_model.setIconSize(QtCore.QSize(40, 30))
        self.toolButton_model.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton_model.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_model.setAutoRaise(False)
        self.toolButton_model.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_model.setObjectName("toolButton_model")
        self.toolButton_video = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_video.setGeometry(QtCore.QRect(16, 282, 30, 30))
        self.toolButton_video.setMinimumSize(QtCore.QSize(28, 25))
        self.toolButton_video.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton_video.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_video.setAutoFillBackground(False)
        self.toolButton_video.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(0, 170, 255);\n"
"color:rgb(0, 170, 255);")
        self.toolButton_video.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/images_test/video.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_video.setIcon(icon2)
        self.toolButton_video.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_video.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton_video.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_video.setAutoRaise(False)
        self.toolButton_video.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_video.setObjectName("toolButton_video")
        self.textEdit_video = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_video.setGeometry(QtCore.QRect(52, 282, 283, 30))
        self.textEdit_video.setMinimumSize(QtCore.QSize(0, 30))
        self.textEdit_video.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(12)
        self.textEdit_video.setFont(font)
        self.textEdit_video.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.textEdit_video.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(0, 170, 255);\n"
"color:rgb(0, 170, 255);")
        self.textEdit_video.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_video.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_video.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textEdit_video.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_video.setReadOnly(True)
        self.textEdit_video.setObjectName("textEdit_video")
        self.textEdit_file = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_file.setGeometry(QtCore.QRect(52, 328, 283, 30))
        self.textEdit_file.setMinimumSize(QtCore.QSize(0, 30))
        self.textEdit_file.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(12)
        self.textEdit_file.setFont(font)
        self.textEdit_file.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEdit_file.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(0, 170, 255);\n"
"color: rgb(0, 170, 255);")
        self.textEdit_file.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_file.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_file.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textEdit_file.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_file.setReadOnly(True)
        self.textEdit_file.setObjectName("textEdit_file")
        self.toolButton_file = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_file.setGeometry(QtCore.QRect(14, 328, 30, 30))
        self.toolButton_file.setMinimumSize(QtCore.QSize(28, 30))
        self.toolButton_file.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton_file.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_file.setAutoFillBackground(False)
        self.toolButton_file.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(0, 170, 255);\n"
"color:rgb(0, 170, 255);")
        self.toolButton_file.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/images_test/filefold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_file.setIcon(icon3)
        self.toolButton_file.setIconSize(QtCore.QSize(50, 39))
        self.toolButton_file.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton_file.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_file.setAutoRaise(False)
        self.toolButton_file.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_file.setObjectName("toolButton_file")
        self.toolButton_camera = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_camera.setGeometry(QtCore.QRect(14, 374, 30, 30))
        self.toolButton_camera.setMinimumSize(QtCore.QSize(28, 30))
        self.toolButton_camera.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton_camera.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_camera.setAutoFillBackground(False)
        self.toolButton_camera.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(0, 170, 255);\n"
"color:rgb(0, 170, 255);")
        self.toolButton_camera.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/images_test/g1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_camera.setIcon(icon4)
        self.toolButton_camera.setIconSize(QtCore.QSize(50, 39))
        self.toolButton_camera.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton_camera.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_camera.setAutoRaise(False)
        self.toolButton_camera.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_camera.setObjectName("toolButton_camera")
        self.textEdit_camera = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_camera.setGeometry(QtCore.QRect(52, 374, 283, 30))
        self.textEdit_camera.setMinimumSize(QtCore.QSize(0, 30))
        self.textEdit_camera.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(12)
        self.textEdit_camera.setFont(font)
        self.textEdit_camera.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEdit_camera.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(0, 170, 255);\n"
"color: rgb(0, 170, 255);")
        self.textEdit_camera.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_camera.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_camera.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_camera.setReadOnly(True)
        self.textEdit_camera.setTabStopDistance(80.0)
        self.textEdit_camera.setObjectName("textEdit_camera")
        self.toolButton_runing = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_runing.setGeometry(QtCore.QRect(64, 452, 199, 49))
        self.toolButton_runing.setMinimumSize(QtCore.QSize(150, 40))
        self.toolButton_runing.setMaximumSize(QtCore.QSize(200, 50))
        self.toolButton_runing.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_runing.setAutoFillBackground(False)
        self.toolButton_runing.setStyleSheet("background-color: transparent;")
        self.toolButton_runing.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/images_test/runicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_runing.setIcon(icon5)
        self.toolButton_runing.setIconSize(QtCore.QSize(327, 69))
        self.toolButton_runing.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton_runing.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_runing.setAutoRaise(False)
        self.toolButton_runing.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_runing.setObjectName("toolButton_runing")
        self.label_picResult = QtWidgets.QLabel(self.centralwidget)
        self.label_picResult.setGeometry(QtCore.QRect(14, 554, 30, 30))
        self.label_picResult.setMinimumSize(QtCore.QSize(30, 30))
        self.label_picResult.setMaximumSize(QtCore.QSize(30, 30))
        self.label_picResult.setStyleSheet("border-image: url(:/newPrefix/images_test/result.png);")
        self.label_picResult.setText("")
        self.label_picResult.setObjectName("label_picResult")
        self.label_plate_result = QtWidgets.QLabel(self.centralwidget)
        self.label_plate_result.setGeometry(QtCore.QRect(197, 554, 143, 30))
        self.label_plate_result.setMinimumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(13)
        self.label_plate_result.setFont(font)
        self.label_plate_result.setStyleSheet("color: rgb(255, 85, 0);")
        self.label_plate_result.setObjectName("label_plate_result")
        self.label_class = QtWidgets.QLabel(self.centralwidget)
        self.label_class.setGeometry(QtCore.QRect(50, 556, 143, 30))
        self.label_class.setMinimumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(10)
        self.label_class.setFont(font)
        self.label_class.setObjectName("label_class")
        self.label_score_result = QtWidgets.QLabel(self.centralwidget)
        self.label_score_result.setGeometry(QtCore.QRect(198, 606, 131, 30))
        self.label_score_result.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(12)
        self.label_score_result.setFont(font)
        self.label_score_result.setStyleSheet("color: rgb(255, 85, 0);")
        self.label_score_result.setObjectName("label_score_result")
        self.label_picConf = QtWidgets.QLabel(self.centralwidget)
        self.label_picConf.setGeometry(QtCore.QRect(13, 604, 30, 30))
        self.label_picConf.setMaximumSize(QtCore.QSize(30, 30))
        self.label_picConf.setStyleSheet("border-image: url(:/newPrefix/images_test/Score.png);")
        self.label_picConf.setText("")
        self.label_picConf.setObjectName("label_picConf")
        self.label_conf = QtWidgets.QLabel(self.centralwidget)
        self.label_conf.setGeometry(QtCore.QRect(52, 606, 131, 30))
        self.label_conf.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(18)
        self.label_conf.setFont(font)
        self.label_conf.setObjectName("label_conf")
        self.label_picResult_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_picResult_2.setGeometry(QtCore.QRect(14, 654, 30, 30))
        self.label_picResult_2.setMinimumSize(QtCore.QSize(30, 30))
        self.label_picResult_2.setMaximumSize(QtCore.QSize(30, 30))
        self.label_picResult_2.setStyleSheet("border-image: url(:/newPrefix/images_test/tally.png);")
        self.label_picResult_2.setText("")
        self.label_picResult_2.setObjectName("label_picResult_2")
        self.label_class_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_class_2.setGeometry(QtCore.QRect(50, 658, 263, 30))
        self.label_class_2.setMinimumSize(QtCore.QSize(210, 0))
        self.label_class_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(12)
        self.label_class_2.setFont(font)
        self.label_class_2.setObjectName("label_class_2")
        self.label_conf_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_conf_3.setGeometry(QtCore.QRect(53, 744, 40, 30))
        self.label_conf_3.setMinimumSize(QtCore.QSize(40, 30))
        self.label_conf_3.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(18)
        self.label_conf_3.setFont(font)
        self.label_conf_3.setObjectName("label_conf_3")
        self.label_score_x2 = QtWidgets.QLabel(self.centralwidget)
        self.label_score_x2.setGeometry(QtCore.QRect(94, 742, 83, 30))
        self.label_score_x2.setMinimumSize(QtCore.QSize(83, 30))
        self.label_score_x2.setMaximumSize(QtCore.QSize(83, 30))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(12)
        self.label_score_x2.setFont(font)
        self.label_score_x2.setStyleSheet("color: rgb(255, 85, 0);")
        self.label_score_x2.setObjectName("label_score_x2")
        self.label_score_x1 = QtWidgets.QLabel(self.centralwidget)
        self.label_score_x1.setGeometry(QtCore.QRect(94, 700, 83, 30))
        self.label_score_x1.setMinimumSize(QtCore.QSize(83, 30))
        self.label_score_x1.setMaximumSize(QtCore.QSize(83, 30))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(12)
        self.label_score_x1.setFont(font)
        self.label_score_x1.setStyleSheet("color: rgb(255, 85, 0);")
        self.label_score_x1.setObjectName("label_score_x1")
        self.label_conf_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_conf_2.setGeometry(QtCore.QRect(53, 702, 40, 30))
        self.label_conf_2.setMinimumSize(QtCore.QSize(40, 30))
        self.label_conf_2.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(18)
        self.label_conf_2.setFont(font)
        self.label_conf_2.setObjectName("label_conf_2")
        self.label_score_y1 = QtWidgets.QLabel(self.centralwidget)
        self.label_score_y1.setGeometry(QtCore.QRect(242, 698, 83, 30))
        self.label_score_y1.setMinimumSize(QtCore.QSize(83, 30))
        self.label_score_y1.setMaximumSize(QtCore.QSize(83, 30))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(12)
        self.label_score_y1.setFont(font)
        self.label_score_y1.setStyleSheet("color: rgb(255, 85, 0);")
        self.label_score_y1.setObjectName("label_score_y1")
        self.label_score_y2 = QtWidgets.QLabel(self.centralwidget)
        self.label_score_y2.setGeometry(QtCore.QRect(240, 740, 83, 30))
        self.label_score_y2.setMinimumSize(QtCore.QSize(83, 30))
        self.label_score_y2.setMaximumSize(QtCore.QSize(83, 30))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(12)
        self.label_score_y2.setFont(font)
        self.label_score_y2.setStyleSheet("color: rgb(255, 85, 0);")
        self.label_score_y2.setObjectName("label_score_y2")
        self.label_conf_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_conf_5.setGeometry(QtCore.QRect(192, 742, 40, 30))
        self.label_conf_5.setMinimumSize(QtCore.QSize(40, 30))
        self.label_conf_5.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(18)
        self.label_conf_5.setFont(font)
        self.label_conf_5.setObjectName("label_conf_5")
        self.label_conf_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_conf_4.setGeometry(QtCore.QRect(192, 700, 40, 30))
        self.label_conf_4.setMinimumSize(QtCore.QSize(40, 30))
        self.label_conf_4.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(18)
        self.label_conf_4.setFont(font)
        self.label_conf_4.setObjectName("label_conf_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionGoogle_Translate = QtWidgets.QAction(MainWindow)
        self.actionGoogle_Translate.setObjectName("actionGoogle_Translate")
        self.actionHTML_type = QtWidgets.QAction(MainWindow)
        self.actionHTML_type.setObjectName("actionHTML_type")
        self.actionsoftware_version = QtWidgets.QAction(MainWindow)
        self.actionsoftware_version.setObjectName("actionsoftware_version")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Plate Recognition "))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "序号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "画面标识"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "车牌"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "位置"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "置信度"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_display.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_location.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">输入图像：</span></p></body></html>"))
        self.label_title.setToolTip(_translate("MainWindow", "<html><head/><body><p></p><p><span style=\" font-style:italic;\"></span></p><p><span style=\" font-style:italic;\">version: </span></p></body></html>"))
        self.label_title.setText(_translate("MainWindow", "车牌识别与管理系统"))
        self.label_class_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\"></span><span style=\" font-size:8pt; font-style:italic; text-decoration: underline;\"></span></p><p><span style=\" font-size:8pt;\"></span></p></body></html>"))
        self.textEdit_model.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'华文仿宋\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Adobe Devanagari\'; font-size:11pt;\">请选择车牌文件夹</span></p></body></html>"))
        self.textEdit_video.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'华文仿宋\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Adobe Devanagari\'; font-size:11pt;\">选择车牌视频文件</span></p></body></html>"))
        self.textEdit_file.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'华文仿宋\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Adobe Devanagari\'; font-size:11pt;\">选择车牌照片文件</span></p></body></html>"))
        self.textEdit_camera.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'华文仿宋\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Adobe Devanagari\'; font-size:11pt;\">开启摄像设备识别</span></p></body></html>"))
        self.label_plate_result.setText(_translate("MainWindow", "省X00000"))
        self.label_class.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">识别结果：</span></p></body></html>"))
        self.label_score_result.setText(_translate("MainWindow", "0"))
        self.label_conf.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Score：</span></p></body></html>"))
        self.label_class_2.setText(_translate("MainWindow", "<html><head/><body><p>车牌位置：</p></body></html>"))
        self.label_conf_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">x2：</span></p></body></html>"))
        self.label_score_x2.setText(_translate("MainWindow", "0"))
        self.label_score_x1.setText(_translate("MainWindow", "0"))
        self.label_conf_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">x1</span><span style=\" font-size:12pt;\">：</span></p></body></html>"))
        self.label_score_y1.setText(_translate("MainWindow", "0"))
        self.label_score_y2.setText(_translate("MainWindow", "0"))
        self.label_conf_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">y2：</span></p></body></html>"))
        self.label_conf_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">y1：</span></p></body></html>"))
        self.actionGoogle_Translate.setText(_translate("MainWindow", "Google Translate"))
        self.actionHTML_type.setText(_translate("MainWindow", "HTML type"))
        self.actionsoftware_version.setText(_translate("MainWindow", "software version"))
import image1_rc
